name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - uses: totto2727-org/monorepo/.github/actions/setup-moonbit@main
      - uses: totto2727-org/monorepo/.github/actions/check-moonbit@main
