name: Publish every Git push to main to FlakeHub

on:
  push:
    branches:
      - main

jobs:
  flakehub-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@050a0db1c73bfd8ddc0816c2c6414fd3d03fabf4
      - uses: totto2727-org/monorepo/.github/actions/publish-flakehub@050a0db1c73bfd8ddc0816c2c6414fd3d03fabf4
